#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <ble_uart_icons.h>

int32_t ble_uart_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm ble_uart!");

    return 0;
}
