#include <furi.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/menu.h>
#include <gui/modules/popup.h>

#define TAG "ble-uart"

// Referenced guide and code from https://instantiator.dev/post/flipper-zero-app-tutorial-02/

/* generated by fbt from .png files in images folder */
#include <ble_uart_icons.h>

/** ids for all scenes used by the app */
typedef enum {
    Ble_UartScene_MainMenu,
    Ble_UartScene_BleConnect,
    Ble_UartScene_BleTerminal,
    Ble_UartScene_count
} Ble_UartScene;

/** ids for the 2 types of view used by the app */
typedef enum { Ble_UartView_Menu, Ble_UartViewPopup } Ble_UartView;

/** The app context struct */
typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Menu* menu;
    Popup* popup;
} Ble_Uart;

/** all custom events */
typedef enum { Ble_Uart_ShowBleConnectPopup, Ble_Uart_ShowBleTerminalPopup } Ble_UartAppEvent;

/* ---------- main menu scene ---------- */

/** indices for menu items */
typedef enum {
    Ble_Uart_Selection_MenuBleConnect,
    Ble_Uart_Selection_MenuBleTerminal
} Ble_Uart_Selection;

/** main menu callback - sends a custom event to the scene manager based on the menu selection */
