#include <furi.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/menu.h>
#include <gui/modules/popup.h>

#define TAG "ble-friend-uart"

// Referenced guide and code from https://instantiator.dev/post/flipper-zero-app-tutorial-02/

/* generated by fbt from .png files in images folder */
#include <ble_uart_icons.h>

/** ids for all scenes used by the app */
typedef enum {
    Ble_Friend_Uart_Scene_MainMenu,
    Ble_Friend_Uart_Scene_Connect,
    Ble_Friend_Uart_Scene_Terminal,
    Ble_Friend_Uart_Scene_count
} Ble_Friend_Uart_Scene;

/** ids for the 2 types of view used by the app */
typedef enum { Ble_Friend_Uart_View_Menu, Ble_Friend_Uart_ViewPopup } Ble_Friend_Uart_View;

/** The app context struct */
struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Menu* menu;
    Popup* popup;
} Ble_Friend_Uart;

/** all custom events */
typedef enum {
    Ble_Friend_Uart_Show_Connect_Popup,
    Ble_Friend_Uart_Show_Terminal_Popup
} Ble_Friend_Uart_AppEvent;

/* ---------- main menu scene ---------- */

/** indices for menu items */
typedef enum {
    Ble_Friend_Uart_Connect_Selection,
    Ble_Friend_Uart_Terminal_Selection
} Ble_Friend_Uart_Selection;

/** main menu callback - sends a custom event to the scene manager based on the menu selection */
void test_app_menu_callback_main_menu(void* context, uint32_t index) {
    FURI_LOG_T(TAG, "test_app_menu_callback_main_menu");
    Ble_Friend_Uart* app = context;
    switch(index) {
    case Ble_Friend_Uart_Connect_Selection:
        scene_manager_handle_custom_event(app->scene_manager, Ble_Friend_Uart_Show_Connect_Popup);
        break;
    case Ble_Friend_Uart_Terminal_Selection:
        scene_manager_handle_custom_event(app->scene_manager, Ble_Friend_Uart_Show_Terminal_Popup);
        break;
    }
}

/** resets the menu, gives it content, callbacks and selection enums */
void test_app_scene_on_enter_main_menu(void* context) {
    FURI_LOG_T(TAG, "test_app_scene_on_enter_main_menu");
    Ble_Friend_Uart* app = context;
    menu_reset(app->menu);